#!/usr/bin/env tsx
// Builds the ONE-FILE variants of the dashboard CLI for environments where npm (or
// this repo) isn't available:
//
//   dist-standalone/bzm-vitals-dashboard.mjs — plain JavaScript. The portable one:
//     node bzm-vitals-dashboard.mjs --artifacts <zip-or-folder> --out report.html
//     runs on any Node >= 20 with no flags, no npm, no tsx — fully offline.
//   dist-standalone/bzm-vitals-dashboard.ts  — the same code as TypeScript:
//     npx tsx bzm-vitals-dashboard.ts --master <masterId> --out report.html
//     # or on Node >= 23.6 (>= 22.6 with --experimental-strip-types):
//     node bzm-vitals-dashboard.ts --master <masterId> --out report.html
//
// The dashboard is authored as several src modules reachable from src/cli.ts, and
// depends on the sibling bzm-vitals-format package. This script inlines the whole
// graph into one file the same way the collector's build-standalone.ts does, and
// cannot silently drift:
//
//   1. Read the REAL sources at build time — every module reachable from src/cli.ts
//      via relative imports, plus ../format/src/index.ts. Nothing is copied by hand.
//   2. Collect them in dependency order, strip every relative import and every
//      'bzm-vitals-format' import (the referenced symbols are inlined, so the bare
//      names resolve), hoist the remaining node-builtin imports to the top — MERGED
//      per module specifier, because two dashboard modules may import overlapping
//      names (e.g. existsSync) and duplicate bindings would not parse — and splice
//      the format source in once at the top.
//   3. Transpile that one file to .mjs with the typescript compiler — type erasure
//      only, at BUILD time; the emitted .mjs needs nothing but node.
//   4. FAIL LOUDLY if the shape ever drifts: only 'node:'-prefixed imports may be
//      hoisted (anything else would need an npm install, defeating the point), the
//      format source must be import-free, no relative/format import or re-export may
//      survive the splice, and the inlined sources may not declare colliding
//      top-level names. A drift breaks the BUILD, not the artifact.
//
// The emitted files are BUILD ARTIFACTS (gitignored), regenerated by this script and
// by test/standalone.test.ts before every run — so a stale copy can never be what
// gets tested.

import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import ts from 'typescript';

const HERE = dirname(fileURLToPath(import.meta.url));
const DASHBOARD_DIR = join(HERE, '..');
const ENTRY = join(DASHBOARD_DIR, 'src', 'cli.ts');
const FORMAT_SRC = join(DASHBOARD_DIR, '..', 'format', 'src', 'index.ts');
const OUT_DIR = join(DASHBOARD_DIR, 'dist-standalone');
const OUT_FILE = join(OUT_DIR, 'bzm-vitals-dashboard.ts');
const OUT_FILE_MJS = join(OUT_DIR, 'bzm-vitals-dashboard.mjs');

const FORMAT_PACKAGE = 'bzm-vitals-format';

/**
 * A full import statement — default and/or named clause, single- or multi-line
 * braces: `import [type] [Default,] [{ … }] from '…';`
 */
const IMPORT_RE =
  /^import\s+(?:type\s+)?(?:([A-Za-z_$][\w$]*)\s*,\s*)?(?:([A-Za-z_$][\w$]*)|\{([\s\S]*?)\})\s+from\s+'([^']+)';[ \t]*$/gm;

/** A relative re-export (`export … from './x.js'`) — must not survive the splice. */
const REEXPORT_RE = /^export\s+(?:type\s+)?(?:\*|\{[\s\S]*?\})\s+from\s+'([^']+)';[ \t]*$/gm;

/** True for a specifier the splice must DROP: the format package, or a relative sibling. */
function isInlinedSpecifier(spec: string): boolean {
  return spec === FORMAT_PACKAGE || spec.startsWith('.');
}

/** Top-level declared names (const/function/interface/type/class/enum), for collision detection. */
function topLevelNames(source: string): string[] {
  const re = /^(?:export\s+)?(?:declare\s+)?(?:const|let|var|function|interface|class|enum|type)\s+([A-Za-z_$][\w$]*)/gm;
  const names: string[] = [];
  for (const m of source.matchAll(re)) names.push(m[1]!);
  return names;
}

/** Resolve a relative specifier ('./cache.js') from a module to its .ts source path. */
function resolveRelative(fromFile: string, spec: string): string {
  const base = resolve(dirname(fromFile), spec);
  return base.replace(/\.js$/, '.ts');
}

interface Module {
  path: string;
  source: string;
}

/**
 * Every dashboard module reachable from `entry` via relative imports, in dependency
 * order (a module appears before the ones that import it) with no duplicates.
 */
async function collectModules(entry: string): Promise<Module[]> {
  const seen = new Set<string>();
  const ordered: Module[] = [];
  async function visit(path: string): Promise<void> {
    if (seen.has(path)) return;
    seen.add(path);
    const source = await readFile(path, 'utf8');
    for (const m of source.matchAll(IMPORT_RE)) {
      const spec = m[4]!;
      if (spec.startsWith('.')) await visit(resolveRelative(path, spec)); // deps first
    }
    ordered.push({ path, source }); // post-order → dependencies precede dependents
  }
  await visit(entry);
  return ordered;
}

/** Per-specifier accumulator for the merged hoisted imports. */
interface MergedImport {
  defaultName?: string;
  /** Binding text keyed by value name — 'existsSync', 'type Credentials', 'X as Y'. */
  named: Map<string, string>;
}

/**
 * Record one import statement's bindings. A `type X` and plain `X` for the same
 * name merge to the plain (value) form, which covers both uses.
 */
function mergeImport(
  into: Map<string, MergedImport>,
  spec: string,
  wholeStmt: string,
  defaultName: string | undefined,
  namedClause: string | undefined,
): void {
  const entry = into.get(spec) ?? { named: new Map() };
  if (defaultName !== undefined) {
    if (entry.defaultName !== undefined && entry.defaultName !== defaultName) {
      throw new Error(
        `Two different default-import names for '${spec}' (${entry.defaultName} vs ${defaultName}).`,
      );
    }
    entry.defaultName = defaultName;
  }
  const statementIsTypeOnly = /^import\s+type\s/.test(wholeStmt);
  if (namedClause !== undefined) {
    for (const rawBinding of namedClause.split(',')) {
      const binding = rawBinding.trim().replace(/\s+/g, ' ');
      if (binding === '') continue;
      const isType = statementIsTypeOnly || binding.startsWith('type ');
      const bare = binding.replace(/^type\s+/, '');
      const key = bare; // 'X' or 'X as Y' — the local binding identity
      const existing = entry.named.get(key);
      if (existing === undefined || (existing.startsWith('type ') && !isType)) {
        entry.named.set(key, isType ? `type ${bare}` : bare);
      }
    }
  }
  into.set(spec, entry);
}

function renderMergedImports(merged: Map<string, MergedImport>): string {
  const lines: string[] = [];
  for (const spec of [...merged.keys()].sort()) {
    const { defaultName, named } = merged.get(spec)!;
    const clauses: string[] = [];
    if (defaultName !== undefined) clauses.push(defaultName);
    if (named.size > 0) clauses.push(`{ ${[...named.values()].sort().join(', ')} }`);
    lines.push(`import ${clauses.join(', ')} from '${spec}';`);
  }
  return lines.join('\n');
}

export interface StandaloneBuild {
  /** Absolute path of the emitted dist-standalone/bzm-vitals-dashboard.ts. */
  outFile: string;
  /** The emitted source, for callers that want to copy it elsewhere. */
  source: string;
  /** Absolute path of the emitted dist-standalone/bzm-vitals-dashboard.mjs. */
  mjsFile: string;
  /** The emitted plain-JavaScript source. */
  mjsSource: string;
}

/** The generated-file banner, with usage lines for the variant it heads. */
function banner(file: string, pkg: { name: string; version: string }, usage: string[]): string {
  return [
    '// =============================================================================',
    `// ${file} — STANDALONE build of the BlazeMeter web-vitals dashboard CLI`,
    '//',
    `// ${pkg.name} v${pkg.version} — built ${new Date().toISOString()}`,
    '//',
    '// Turns a finished BlazeMeter Playwright run (with the bzm-playwright-vitals',
    '// collector aboard) into ONE self-contained report.html. Usage:',
    '//',
    ...usage.map((line) => `//   ${line}`.trimEnd()),
    '//',
    '// --artifacts reads downloaded artifacts (a zip, an unzipped folder, or a folder',
    '// of either): no network, no credentials. --master fetches from the API and',
    '// caches in ./.artifact-cache — a re-run against the same master does zero',
    '// network calls and needs no credentials.',
    '//',
    '// DO NOT HAND-EDIT. This file is GENERATED by',
    '//   packages/dashboard/scripts/build-standalone.ts   (npm run build:standalone)',
    '// from packages/dashboard/src/*.ts with bzm-vitals-format inlined. It is not a',
    '// second source of truth.',
    '// =============================================================================',
    '',
  ].join('\n');
}

/** Erase the types from the spliced .ts — nothing else changes. */
function transpileToMjs(tsSource: string): string {
  const out = ts.transpileModule(tsSource, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      removeComments: false,
    },
    reportDiagnostics: true,
  });
  const errors = (out.diagnostics ?? []).filter((d) => d.category === ts.DiagnosticCategory.Error);
  if (errors.length > 0) {
    const text = errors.map((d) => ts.flattenDiagnosticMessageText(d.messageText, '\n')).join('\n');
    throw new Error(`Transpiling the standalone file to .mjs failed:\n${text}`);
  }
  return out.outputText;
}

export async function buildStandalone(): Promise<StandaloneBuild> {
  const [formatSource, pkgJson] = await Promise.all([
    readFile(FORMAT_SRC, 'utf8'),
    readFile(join(DASHBOARD_DIR, 'package.json'), 'utf8'),
  ]);
  const pkg = JSON.parse(pkgJson) as { name: string; version: string };
  const modules = await collectModules(ENTRY);

  // --- Guard: the format source must be self-contained (constants + types only).
  if (/^\s*import\s/m.test(formatSource)) {
    throw new Error(
      `${FORMAT_SRC} now contains an import statement; the standalone splice assumes ` +
        'a dependency-free format module. Update scripts/build-standalone.ts.',
    );
  }

  // --- Guard: no top-level name collisions across format + every inlined module.
  const seenNames = new Map<string, string>(); // name -> first source label
  for (const src of [{ path: FORMAT_SRC, source: formatSource }, ...modules]) {
    for (const name of topLevelNames(src.source)) {
      const prior = seenNames.get(name);
      if (prior !== undefined) {
        throw new Error(
          `Top-level name collision '${name}' between ${prior} and ${src.path}. ` +
            'The splice would produce duplicate declarations.',
        );
      }
      seenNames.set(name, src.path);
    }
  }

  // --- Split each module into (hoisted imports, body): drop format + relative
  //     imports, merge node-builtin imports per specifier. Bodies keep everything
  //     else verbatim, minus cli.ts's shebang (illegal anywhere but byte 0).
  const merged = new Map<string, MergedImport>();
  const bodies: string[] = [];
  let sawFormatImport = false;
  for (const mod of modules) {
    const body = mod.source
      .replace(/^#![^\n]*\n/, '')
      .replace(IMPORT_RE, (stmt, defaultName: string | undefined, loneDefault: string | undefined, namedClause: string | undefined, spec: string) => {
        if (spec === FORMAT_PACKAGE) sawFormatImport = true;
        if (isInlinedSpecifier(spec)) {
          // Symbol is inlined below — drop the import. An alias would silently
          // lose its binding (the inlined declaration has the original name).
          if (namedClause !== undefined && /\bas\b/.test(namedClause)) {
            throw new Error(
              `Module ${mod.path} imports '${spec}' with an alias; alias in code ` +
                `(const X = Y) instead — the splice drops this import statement.`,
            );
          }
          return '';
        }
        if (!spec.startsWith('node:')) {
          throw new Error(
            `Module ${mod.path} imports '${spec}', which is neither inlined nor a node ` +
              'builtin — the standalone file must resolve with no npm install.',
          );
        }
        mergeImport(merged, spec, stmt, defaultName ?? loneDefault, namedClause);
        return '';
      });
    if (REEXPORT_RE.test(body)) {
      throw new Error(`Module ${mod.path} contains a re-export; the splice cannot carry it.`);
    }
    bodies.push(
      [
        '// ---------------------------------------------------------------------------',
        `// Inlined from ${mod.path.slice(DASHBOARD_DIR.length + 1)}`,
        '// ---------------------------------------------------------------------------',
        body.replace(/^\n+/, ''),
      ].join('\n'),
    );
  }

  // --- Guard: the dashboard really does depend on the format package (else this
  //     script is inlining the wrong thing, or a rename slipped through).
  if (!sawFormatImport) {
    throw new Error(
      `No import from '${FORMAT_PACKAGE}' found in the dashboard sources; the standalone ` +
        'build expects the format package to be a dependency. Update scripts/build-standalone.ts.',
    );
  }

  const formatBlock = [
    '// ---------------------------------------------------------------------------',
    `// Inlined from ${FORMAT_PACKAGE} (packages/format/src/index.ts) at build time.`,
    '// ---------------------------------------------------------------------------',
    formatSource.trimEnd(),
    '// --------------------------- end inlined format ---------------------------',
  ].join('\n');

  const header = banner('bzm-vitals-dashboard.ts', pkg, [
    'export BLAZEMETER_API_KEY=path/to/api-key.json   # or _ID / _SECRET vars',
    'npx tsx bzm-vitals-dashboard.ts --master <masterId> --out report.html',
    '',
    '# zero-install on Node >= 23.6 (>= 22.6 needs --experimental-strip-types):',
    'node bzm-vitals-dashboard.ts --master <masterId> --out report.html',
    '',
    '# offline, from downloaded artifacts:',
    'node bzm-vitals-dashboard.ts --artifacts <zip-or-folder> --out report.html',
    '',
    '# older Node, or no type stripping? Use bzm-vitals-dashboard.mjs instead.',
  ]);

  const source = [header, renderMergedImports(merged), '', formatBlock, '', bodies.join('\n\n')].join('\n');

  // --- Guard: no ACTUAL import of the format package or a relative sibling may
  //     survive the splice — either would fail to resolve next to a download.
  for (const m of source.matchAll(new RegExp(IMPORT_RE.source, 'gm'))) {
    if (isInlinedSpecifier(m[4]!)) {
      throw new Error(
        `An import from '${m[4]}' survived the splice — the standalone file would not ` +
          'resolve on its own. Update scripts/build-standalone.ts.',
      );
    }
  }

  // --- The plain-JavaScript twin: the same spliced body, types erased. The
  //     banner is swapped for one with .mjs usage; the shebang makes it
  //     directly executable after chmod on a Unix download.
  const body = source.slice(header.length);
  const mjsHeader = banner('bzm-vitals-dashboard.mjs', pkg, [
    '# offline, from downloaded artifacts — no network, no credentials:',
    'node bzm-vitals-dashboard.mjs --artifacts <zip-or-folder> --out report.html',
    '',
    '# from the BlazeMeter API:',
    'export BLAZEMETER_API_KEY=path/to/api-key.json   # or _ID / _SECRET vars',
    'node bzm-vitals-dashboard.mjs --master <masterId> --out report.html',
    '',
    'Plain JavaScript: any Node >= 20, no flags, no npm install, no tsx.',
  ]);
  const mjsSource = `#!/usr/bin/env node\n${mjsHeader}${transpileToMjs(body)}`;

  // --- Guard: type erasure must not have left (or introduced) a non-builtin import.
  for (const m of mjsSource.matchAll(/^import\s[^;]*?from\s+'([^']+)';/gm)) {
    if (!m[1]!.startsWith('node:')) {
      throw new Error(`The .mjs imports '${m[1]}' — it must resolve from node builtins alone.`);
    }
  }

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_FILE, source, 'utf8');
  await writeFile(OUT_FILE_MJS, mjsSource, 'utf8');
  await chmod(OUT_FILE_MJS, 0o755);

  return { outFile: OUT_FILE, source, mjsFile: OUT_FILE_MJS, mjsSource };
}

// CLI entry (npm run build:standalone). Guarded so the harness can import buildStandalone.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  buildStandalone()
    .then(({ outFile, mjsFile }) => {
      console.log(`standalone dashboard written: ${outFile}`);
      console.log(`standalone dashboard written: ${mjsFile}`);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
