#!/usr/bin/env tsx
// Builds dist-standalone/bzm-vitals.ts — the ONE-FILE variant of the collector that can
// be uploaded directly to a BlazeMeter test next to a spec, no npm publish needed:
//
//   import { test, expect } from './bzm-vitals';
//
// How it works, and why it cannot silently drift from @bzm/vitals-format:
//
//   1. Read the REAL collector source (src/index.ts) and the REAL format source
//      (../format/src/index.ts) at build time. Nothing is copied by hand.
//   2. Find the collector's single `import { ... } from '@bzm/vitals-format'` statement
//      and splice the entire format source in its place. The format file is small,
//      dependency-free constants + types, so inlining it verbatim is exact: same
//      SCHEMA_VERSION, same prefixes, same types the package builds against.
//   3. FAIL LOUDLY if the shape ever changes: exactly one format import must exist, no
//      reference to '@bzm/vitals-format' may survive the splice, the format source must
//      itself be import-free, and the two sources may not declare colliding top-level
//      names. A drift in either source breaks the BUILD, not the artifact.
//
// The emitted file is a BUILD ARTIFACT (gitignored), regenerated by this script and by
// the Seam 1 harness (test/standalone.test.ts) before every run — so a stale copy can
// never be what gets tested.
//
// Engine constraint: Playwright's own TS loader transpiles the uploaded spec and its
// relative TS imports. The output therefore contains no tsconfig-path imports, no
// .js-extension self-imports, and no top-level await — only '@playwright/test' and
// node builtins, both present on every BlazeMeter Playwright Engine.

import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const COLLECTOR_DIR = join(HERE, '..');
const COLLECTOR_SRC = join(COLLECTOR_DIR, 'src', 'index.ts');
const FORMAT_SRC = join(COLLECTOR_DIR, '..', 'format', 'src', 'index.ts');
const OUT_DIR = join(COLLECTOR_DIR, 'dist-standalone');
const OUT_FILE = join(OUT_DIR, 'bzm-vitals.ts');
const UPLOAD_KIT_COPY = join(COLLECTOR_DIR, 'upload-kit', 'bzm-vitals.ts');

const FORMAT_PACKAGE = '@bzm/vitals-format';

/** Top-level declared names (const/function/interface/type/class/enum), for collision detection. */
function topLevelNames(source: string): string[] {
  const re = /^(?:export\s+)?(?:declare\s+)?(?:const|let|var|function|interface|class|enum|type)\s+([A-Za-z_$][\w$]*)/gm;
  const names: string[] = [];
  for (const m of source.matchAll(re)) names.push(m[1]!);
  return names;
}

export interface StandaloneBuild {
  /** Absolute path of the emitted dist-standalone/bzm-vitals.ts. */
  outFile: string;
  /** The emitted source, for callers that want to copy it elsewhere. */
  source: string;
}

export async function buildStandalone(): Promise<StandaloneBuild> {
  const [collectorSource, formatSource, pkgJson] = await Promise.all([
    readFile(COLLECTOR_SRC, 'utf8'),
    readFile(FORMAT_SRC, 'utf8'),
    readFile(join(COLLECTOR_DIR, 'package.json'), 'utf8'),
  ]);
  const pkg = JSON.parse(pkgJson) as { name: string; version: string };

  // --- Guard: the format source must be self-contained (constants + types only).
  if (/^\s*import\s/m.test(formatSource)) {
    throw new Error(
      `${FORMAT_SRC} now contains an import statement; the standalone splice assumes ` +
        'a dependency-free format module. Update scripts/build-standalone.ts.',
    );
  }

  // --- Guard: exactly one import from the format package, matched in full.
  const importRe = /^import\s+\{[^}]*\}\s+from\s+'@bzm\/vitals-format';\s*$/gm;
  const matches = collectorSource.match(importRe) ?? [];
  if (matches.length !== 1) {
    throw new Error(
      `Expected exactly one import from '${FORMAT_PACKAGE}' in ${COLLECTOR_SRC}, ` +
        `found ${matches.length}. Update scripts/build-standalone.ts.`,
    );
  }

  // --- Guard: no top-level name collisions between the two spliced sources.
  const formatNames = new Set(topLevelNames(formatSource));
  const collisions = topLevelNames(collectorSource).filter((n) => formatNames.has(n));
  if (collisions.length > 0) {
    throw new Error(
      `Top-level name collision between collector and format sources: ${collisions.join(', ')}. ` +
        'The splice would produce duplicate declarations.',
    );
  }

  const spliced = collectorSource.replace(
    importRe,
    [
      '// ---------------------------------------------------------------------------',
      `// Inlined from ${FORMAT_PACKAGE} (packages/format/src/index.ts) at build time.`,
      '// ---------------------------------------------------------------------------',
      formatSource.trimEnd(),
      '// --------------------------- end inlined format ---------------------------',
    ].join('\n'),
  );

  // --- Guard: no import/require of the workspace package may survive the splice.
  // (Prose mentions in comments are fine — only module resolution matters on the Engine.)
  if (/(?:from\s+|require\()\s*['"]@bzm\/vitals-format['"]/.test(spliced)) {
    throw new Error(
      `A reference to '${FORMAT_PACKAGE}' survived the splice — the standalone file ` +
        'would not resolve on an Engine. Update scripts/build-standalone.ts.',
    );
  }

  const header = [
    '// =============================================================================',
    '// bzm-vitals.ts — STANDALONE build of the BlazeMeter Playwright vitals collector',
    '//',
    `// ${pkg.name} v${pkg.version} — built ${new Date().toISOString()}`,
    '//',
    '// DO NOT HAND-EDIT. This file is GENERATED by',
    '//   packages/collector/scripts/build-standalone.ts   (npm run build:standalone)',
    '// from packages/collector/src/index.ts with @bzm/vitals-format inlined. It is a',
    '// build artifact for DIRECT-UPLOAD VALIDATION — upload it to a BlazeMeter test',
    '// next to a spec that does:',
    "//   import { test, expect } from './bzm-vitals';",
    '// It is not a second source of truth; adopt via npm when published.',
    '// =============================================================================',
    '',
  ].join('\n');

  const source = header + spliced;

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_FILE, source, 'utf8');
  // Keep the upload kit's copy in lockstep with the artifact.
  await mkdir(dirname(UPLOAD_KIT_COPY), { recursive: true });
  await copyFile(OUT_FILE, UPLOAD_KIT_COPY);

  return { outFile: OUT_FILE, source };
}

// CLI entry (npm run build:standalone). Guarded so the harness can import buildStandalone.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  buildStandalone()
    .then(({ outFile }) => {
      console.log(`standalone collector written: ${outFile}`);
      console.log(`upload-kit copy refreshed:    ${UPLOAD_KIT_COPY}`);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
