#!/usr/bin/env tsx
// Builds dist-standalone/bzm-playwright-vitals.ts — the ONE-FILE variant of the collector that can
// be uploaded directly to a BlazeMeter test next to a spec, no npm publish needed:
//
//   import { test, expect } from './bzm-playwright-vitals';
//
// The collector is authored as several src modules (index + pusher + blazemeter-destination),
// and depends on the sibling bzm-vitals-format package. The Engine upload must be a SINGLE
// file, so this script inlines the whole graph into one, and cannot silently drift:
//
//   1. Read the REAL sources at build time — every collector module reachable from
//      src/index.ts via relative imports, plus ../format/src/index.ts. Nothing is copied
//      by hand.
//   2. Collect them in dependency order (a module before the modules that import it), strip
//      every relative import and every 'bzm-vitals-format' import (the referenced symbols
//      are inlined, so the bare names resolve), hoist the remaining imports (node builtins
//      and '@playwright/test') to the top, and splice the format source in once at the top.
//   3. FAIL LOUDLY if the shape ever drifts: the format source must be import-free, no
//      relative or format import may survive the splice, and the inlined sources may not
//      declare colliding top-level names. A drift breaks the BUILD, not the artifact.
//
// The emitted file is a BUILD ARTIFACT (gitignored), regenerated by this script and by
// the Seam 1 harness (test/standalone.test.ts) before every run — so a stale copy can
// never be what gets tested.
//
// Engine constraint: Playwright's own TS loader transpiles the uploaded spec and its
// relative TS imports. The output therefore contains no tsconfig-path imports, no
// .js-extension self-imports, and no top-level await — only '@playwright/test' and
// node builtins, both present on every BlazeMeter Playwright Engine.

import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const COLLECTOR_DIR = join(HERE, '..');
const COLLECTOR_ENTRY = join(COLLECTOR_DIR, 'src', 'index.ts');
const FORMAT_SRC = join(COLLECTOR_DIR, '..', 'format', 'src', 'index.ts');
const OUT_DIR = join(COLLECTOR_DIR, 'dist-standalone');
const OUT_FILE = join(OUT_DIR, 'bzm-playwright-vitals.ts');
const UPLOAD_KIT_COPY = join(COLLECTOR_DIR, 'upload-kit', 'bzm-playwright-vitals.ts');

const FORMAT_PACKAGE = 'bzm-vitals-format';

/** A full `import [type] { … } from '…';` statement (single- or multi-line braces). */
const IMPORT_RE = /^import\s+(?:type\s+)?\{[\s\S]*?\}\s+from\s+'([^']+)';[ \t]*$/gm;

/** True for a specifier the splice must DROP: the format package, or a relative sibling. */
function isInlinedSpecifier(spec: string): boolean {
  return spec === FORMAT_PACKAGE || spec.startsWith('.');
}

/** Top-level declared names (const/function/interface/type/class/enum), for collision detection. */
function topLevelNames(source: string): string[] {
  const re = /^(?:export\s+)?(?:declare\s+)?(?:const|let|var|function|interface|class|enum|type)\s+([A-Za-z_$][\w$]*)/gm;
  const names: string[] = [];
  for (const m of source.matchAll(re)) names.push(m[1]!);
  return names;
}

/** Resolve a relative specifier ('./pusher.js') from a module to its .ts source path. */
function resolveRelative(fromFile: string, spec: string): string {
  const base = resolve(dirname(fromFile), spec);
  return base.replace(/\.js$/, '.ts');
}

interface Module {
  path: string;
  source: string;
}

/**
 * Every collector module reachable from `entry` via relative imports, in dependency
 * order (a module appears before the ones that import it) with no duplicates.
 */
async function collectModules(entry: string): Promise<Module[]> {
  const seen = new Set<string>();
  const ordered: Module[] = [];
  async function visit(path: string): Promise<void> {
    if (seen.has(path)) return;
    seen.add(path);
    const source = await readFile(path, 'utf8');
    for (const m of source.matchAll(IMPORT_RE)) {
      const spec = m[1]!;
      if (spec.startsWith('.')) await visit(resolveRelative(path, spec)); // deps first
    }
    ordered.push({ path, source }); // post-order → dependencies precede dependents
  }
  await visit(entry);
  return ordered;
}

export interface StandaloneBuild {
  /** Absolute path of the emitted dist-standalone/bzm-playwright-vitals.ts. */
  outFile: string;
  /** The emitted source, for callers that want to copy it elsewhere. */
  source: string;
}

export async function buildStandalone(): Promise<StandaloneBuild> {
  const [formatSource, pkgJson] = await Promise.all([
    readFile(FORMAT_SRC, 'utf8'),
    readFile(join(COLLECTOR_DIR, 'package.json'), 'utf8'),
  ]);
  const pkg = JSON.parse(pkgJson) as { name: string; version: string };
  const modules = await collectModules(COLLECTOR_ENTRY);

  // --- Guard: the format source must be self-contained (constants + types only).
  if (/^\s*import\s/m.test(formatSource)) {
    throw new Error(
      `${FORMAT_SRC} now contains an import statement; the standalone splice assumes ` +
        'a dependency-free format module. Update scripts/build-standalone.ts.',
    );
  }

  // --- Guard: no top-level name collisions across format + every inlined collector module.
  const seenNames = new Map<string, string>(); // name -> first source label
  for (const src of [{ path: FORMAT_SRC, source: formatSource }, ...modules]) {
    for (const name of topLevelNames(src.source)) {
      const prior = seenNames.get(name);
      if (prior !== undefined) {
        throw new Error(
          `Top-level name collision '${name}' between ${prior} and ${src.path}. ` +
            'The splice would produce duplicate declarations.',
        );
      }
      seenNames.set(name, src.path);
    }
  }

  // --- Split each module into (kept imports, body): drop format + relative imports, keep
  //     node/@playwright imports to hoist. Bodies keep everything else verbatim.
  const keptImports: string[] = [];
  const bodies: string[] = [];
  let sawFormatImport = false;
  for (const mod of modules) {
    const body = mod.source.replace(IMPORT_RE, (stmt, spec: string) => {
      if (spec === FORMAT_PACKAGE) sawFormatImport = true;
      if (isInlinedSpecifier(spec)) return ''; // symbol is inlined below — drop the import
      if (!keptImports.includes(stmt)) keptImports.push(stmt); // node/@playwright — hoist once
      return '';
    });
    bodies.push(
      [
        '// ---------------------------------------------------------------------------',
        `// Inlined from ${mod.path.slice(COLLECTOR_DIR.length + 1)}`,
        '// ---------------------------------------------------------------------------',
        body.replace(/^\n+/, ''),
      ].join('\n'),
    );
  }

  // --- Guard: the collector really does depend on the format package (else this script
  //     is inlining the wrong thing, or a rename slipped through).
  if (!sawFormatImport) {
    throw new Error(
      `No import from '${FORMAT_PACKAGE}' found in the collector sources; the standalone ` +
        'build expects the format package to be a dependency. Update scripts/build-standalone.ts.',
    );
  }

  const formatBlock = [
    '// ---------------------------------------------------------------------------',
    `// Inlined from ${FORMAT_PACKAGE} (packages/format/src/index.ts) at build time.`,
    '// ---------------------------------------------------------------------------',
    formatSource.trimEnd(),
    '// --------------------------- end inlined format ---------------------------',
  ].join('\n');

  const header = [
    '// =============================================================================',
    '// bzm-playwright-vitals.ts — STANDALONE build of the BlazeMeter Playwright vitals collector',
    '//',
    `// ${pkg.name} v${pkg.version} — built ${new Date().toISOString()}`,
    '//',
    '// DO NOT HAND-EDIT. This file is GENERATED by',
    '//   packages/collector/scripts/build-standalone.ts   (npm run build:standalone)',
    '// from packages/collector/src/*.ts with bzm-vitals-format inlined. It is a',
    '// build artifact for DIRECT-UPLOAD VALIDATION — upload it to a BlazeMeter test',
    '// next to a spec that does:',
    "//   import { test, expect } from './bzm-playwright-vitals';",
    '// It is not a second source of truth; adopt via npm when published.',
    '// =============================================================================',
    '',
  ].join('\n');

  const source = [header, keptImports.join('\n'), '', formatBlock, '', bodies.join('\n\n')].join('\n');

  // --- Guard: no ACTUAL import statement (line-anchored, so prose mentions in comments
  //     are fine) of the format package or a relative sibling may survive the splice —
  //     either would fail to resolve on an Engine, whose upload is this one file alone.
  for (const m of source.matchAll(new RegExp(IMPORT_RE.source, 'gm'))) {
    if (isInlinedSpecifier(m[1]!)) {
      throw new Error(
        `An import from '${m[1]}' survived the splice — the standalone file would not ` +
          'resolve on an Engine. Update scripts/build-standalone.ts.',
      );
    }
  }

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_FILE, source, 'utf8');
  // Keep the upload kit's copy in lockstep with the artifact.
  await mkdir(dirname(UPLOAD_KIT_COPY), { recursive: true });
  await copyFile(OUT_FILE, UPLOAD_KIT_COPY);

  return { outFile: OUT_FILE, source };
}

// CLI entry (npm run build:standalone). Guarded so the harness can import buildStandalone.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  buildStandalone()
    .then(({ outFile }) => {
      console.log(`standalone collector written: ${outFile}`);
      console.log(`upload-kit copy refreshed:    ${UPLOAD_KIT_COPY}`);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
